name: Bug Report
description: Report a bug
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Describe the bug
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
      placeholder: Describe the expected behavior
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: e.g., macOS 15.2, Ubuntu 24.04
    validations:
      required: true
  - type: input
    id: go-version
    attributes:
      label: Go version
      placeholder: e.g., 1.25.0
    validations:
      required: false
