name: Feature Request
description: Suggest a feature
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: What would you like?
      placeholder: Describe the feature
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Why?
      placeholder: Describe the use case or problem this would solve
    validations:
      required: true
